FROM solidtestsuite/web-access-control-tests
# RUN git fetch origin
RUN git fetch https://github.com/solid-contrib/web-access-control-tests.git
RUN git pull
RUN git checkout patchAppendNewDocument
RUN git pull
