FROM solidtestsuite/web-access-control-tests
# RUN git fetch origin
RUN git fetch https://github.com/solid-contrib/web-access-control-tests.git patchAppendNewDocument
# RUN git stash
# RUN git pull https://github.com/solid-contrib/web-access-control-tests.git
# RUN git checkout patchAppendNewDocument
# RUN git pull https://github.com/solid-contrib/web-access-control-tests.git
