FROM solidtestsuite/web-access-control-tests
# RUN git fetch origin
RUN git fetch https://github.com/solid-contrib/web-access-control-tests patchAppendNewDocument
RUN git checkout patchAppendNewDocument
RUN git pull
