import debug from 'debug'

export const handlers = debug('solid:handlers')
export const errors = debug('solid:errors')
export const ACL = debug('solid:ACL')
export const cache = debug('solid:cache')
export const parse = debug('solid:parse')
export const metadata = debug('solid:metadata')
export const authentication = debug('solid:authentication')
export const settings = debug('solid:settings')
export const server = debug('solid:server')
export const subscription = debug('solid:subscription')
export const container = debug('solid:container')
export const accounts = debug('solid:accounts')
export const email = debug('solid:email')
export const ldp = debug('solid:ldp')
export const fs = debug('solid:fs')
export const prep = debug('solid:prep')