var debug = require('debug')

exports.handlers = debug('ldnode:handlers')
exports.errors = debug('ldnode:errors')
exports.ACL = debug('ldnode:ACL')
exports.parse = debug('ldnode:parse')
exports.metadata = debug('ldnode:metadata')
exports.authentication = debug('ldnode:authentication')
exports.settings = debug('ldnode:settings')
exports.server = debug('ldnode:server')
exports.subscription = debug('ldnode:subscription')
exports.container = debug('ldnode:container')
exports.idp = debug('ldnode:idp')
