var debug = require('debug')

exports.handlers = debug('solid:handlers')
exports.errors = debug('solid:errors')
exports.ACL = debug('solid:ACL')
exports.parse = debug('solid:parse')
exports.metadata = debug('solid:metadata')
exports.authentication = debug('solid:authentication')
exports.settings = debug('solid:settings')
exports.server = debug('solid:server')
exports.subscription = debug('solid:subscription')
exports.container = debug('solid:container')
exports.idp = debug('solid:idp')
